import './../lib/vue.js'

import './../lib/jsurl.js'
import './../lib/key.js'
import 'https://api.metricq.zih.tu-dresden.de/metricq-history-v2.js'
import './uicode.js'
import './ui/legendApp.js'
import './ui/popupApp.js'
import './ui/configApp.js'
import './ui/exportApp.js'
import './ui/presetApp.js'
import './ui/xaxisApp.js'
import './ui/yaxisApp.js'

import './ui/metric-legend.js'
import './ui/metric-popup.js'
import './ui/popup-header.js'
import './ui/configuration-popup.js'
import './ui/export-popup.js'
import './ui/interaction-array-option.js'
import './ui/preset-popup.js'
import './ui/xaxis-popup.js'
import './ui/yaxis-popup.js'
